apiVersion: apps/v1
kind: Deployment
metadata:
  name: live
  namespace: live
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-io-auth
      initContainers:
        - name: migrate
          image: ghcr.io/mahd-dev/live:latest
          command:
            - "npx"
            - "prisma"
            - "db"
            - "push"
          envFrom:
            - configMapRef:
                name: live
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: live-pg
                  key: superuser-username
            - name: DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: live-pg
                  key: superuser-password
            - name: DATABASE_URL
              value: postgresql://$(DATABASE_USER):$(DATABASE_PASS)@$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_NAME)?schema=$(DB_SCHEMA)
      containers:
        - name: live
          image: ghcr.io/mahd-dev/live:latest
          envFrom:
            - configMapRef:
                name: live
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: live-pg
                  key: superuser-username
            - name: DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: live-pg
                  key: superuser-password
            - name: DATABASE_URL
              value: postgresql://$(DATABASE_USER):$(DATABASE_PASS)@$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_NAME)?schema=$(DB_SCHEMA)
          ports:
            - name: http
              containerPort: 80
