name: Build and Deploy PROD

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          # file: docker/server.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: azure/setup-kubectl@v3
      - uses: imranismail/setup-kustomize@v2
      - run: |
          echo "${{ secrets.MAHD_CLOUD_K8S_KUBECONFIG }}" > ${{ runner.temp }}/kubeconfig
          echo "KUBECONFIG=${{ runner.temp }}/kubeconfig" >> $GITHUB_ENV
      - working-directory: ./k8s/overlays/prod
        run: |
          kustomize edit set image ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.version }}
      - working-directory: ./k8s/common
        run: |
          kubectl apply -k .
      - working-directory: ./k8s/overlays/prod
        run: |
          kubectl apply -k .
      - run: |
          kubectl -n live wait --for=condition=Available deployment/live
